--
-- Why a grant ended: refund | chargeback | lastPaidDay | (Epic 3) revoked.
--
-- ADD-only on purpose. A generate run that DROPS and ADDS on the same table in
-- one pass asks drizzle-kit whether that pair is a rename, needs a TTY for the
-- answer, and dies without writing a file at all.
--
-- Nullable, and no backfill: a grant that ended before this column existed has
-- no recoverable reason, and inventing one is worse than NULL — the Operator
-- would then read a fact nobody ever recorded.
--
ALTER TABLE "grants" ADD COLUMN "ended_reason" text;
